baseurl: http://www.logix.top
#safe: false
#markdown: kramdown
highlighter: pygments #pygments: true

name: Logix's Blog
desc: 金融，编程，探寻开源程序
keyword: logix, blog, 博客, 开源, 技术, web工程师

permalink: /:year/:month/:day/:title.html

#category:
#    plan: 计划
#    test: 测试
