baseurl: http://www.logix.top
#safe: false
#markdown: kramdown
highlighter: pygments #pygments: true

name: Logix's Blog
desc: 探寻开源的价值

permalink: /:year/:month/:day/:title.html

#category:
#    plan: 计划
#    test: 测试
